// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteOneChirp = `-- name: DeleteOneChirp :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteOneChirp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOneChirp, id)
	return err
}

const getAllChirps = `-- name: GetAllChirps :many
SELECT c.id, c.created_at, c.updated_at, c.body, c.user_id, u.username
FROM chirps c
JOIN users u ON u.id = c.user_id
ORDER BY c.created_at ASC
`

type GetAllChirpsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
	Username  string
}

func (q *Queries) GetAllChirps(ctx context.Context) ([]GetAllChirpsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChirpsRow
	for rows.Next() {
		var i GetAllChirpsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllChirpsFromUserID = `-- name: GetAllChirpsFromUserID :many
SELECT c.id, c.created_at, c.updated_at, c.body, c.user_id, u.username
FROM chirps c 
JOIN users u ON u.id = c.user_id 
WHERE c.user_id = $1
ORDER BY c.created_at ASC
`

type GetAllChirpsFromUserIDRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
	Username  string
}

func (q *Queries) GetAllChirpsFromUserID(ctx context.Context, userID uuid.UUID) ([]GetAllChirpsFromUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirpsFromUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChirpsFromUserIDRow
	for rows.Next() {
		var i GetAllChirpsFromUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneChirp = `-- name: GetOneChirp :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE id = $1
`

func (q *Queries) GetOneChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getOneChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
