// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (chirp_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, chirp_id, user_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	ChirpID uuid.UUID
	UserID  uuid.UUID
	Body    string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.ChirpID, arg.UserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ChirpID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments 
WHERE id = $1 AND user_id = $2
RETURNING id, chirp_id, user_id, body, created_at, updated_at
`

type DeleteCommentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, deleteComment, arg.ID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ChirpID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const editComment = `-- name: EditComment :one
UPDATE comments 
SET body = $1, 
    updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, chirp_id, user_id, body, created_at, updated_at
`

type EditCommentParams struct {
	Body   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, editComment, arg.Body, arg.ID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ChirpID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.chirp_id, c.user_id, c.body, c.created_at, c.updated_at, u.username
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID        uuid.UUID
	ChirpID   uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChirpID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getCommentCount = `-- name: GetCommentCount :one
SELECT COUNT(*) AS count 
FROM comments
WHERE chirp_id = $1
`

func (q *Queries) GetCommentCount(ctx context.Context, chirpID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommentCount, chirpID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCommentsByChirpID = `-- name: GetCommentsByChirpID :many
SELECT c.id, c.chirp_id, c.user_id, c.body, c.created_at, c.updated_at, u.username
FROM comments c 
JOIN users u ON u.id = c.user_id
WHERE c.chirp_id = $1
ORDER BY c.created_at ASC
`

type GetCommentsByChirpIDRow struct {
	ID        uuid.UUID
	ChirpID   uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
}

func (q *Queries) GetCommentsByChirpID(ctx context.Context, chirpID uuid.UUID) ([]GetCommentsByChirpIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByChirpID, chirpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByChirpIDRow
	for rows.Next() {
		var i GetCommentsByChirpIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ChirpID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
