// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO email_verification_tokens (
    user_id, expires_at
)
VALUES (
    $1,
    NOW() + INTERVAL '30 days'
)
RETURNING token, user_id, created_at, expires_at
`

func (q *Queries) CreateVerificationToken(ctx context.Context, userID uuid.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createVerificationToken, userID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, token uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationToken, token)
	return err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT u.id, u.username, v.token, v.expires_at
FROM email_verification_tokens v 
JOIN users u ON u.id = v.user_id
WHERE v.token = $1 AND v.expires_at > NOW()
`

type GetUserByVerificationTokenRow struct {
	ID        uuid.UUID
	Username  string
	Token     uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) GetUserByVerificationToken(ctx context.Context, token uuid.UUID) (GetUserByVerificationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByVerificationToken, token)
	var i GetUserByVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
	)
	return i, err
}

const markUserVerified = `-- name: MarkUserVerified :exec
UPDATE users
SET is_verified = true 
WHERE id = $1
`

func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markUserVerified, id)
	return err
}
