// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :one
INSERT INTO followers (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, followee_id) DO NOTHING
RETURNING follower_id, followee_id, created_at, updated_at
`

type FollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	var i Follower
	err := row.Scan(
		&i.FollowerID,
		&i.FolloweeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCountFollowers = `-- name: GetCountFollowers :one
SELECT COUNT(*) AS follower_count
FROM followers 
WHERE followee_id = $1
`

func (q *Queries) GetCountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountFollowers, followeeID)
	var follower_count int64
	err := row.Scan(&follower_count)
	return follower_count, err
}

const getCountFollowings = `-- name: GetCountFollowings :one
SELECT COUNT(*) AS following_count
FROM followers
WHERE follower_id = $1
`

func (q *Queries) GetCountFollowings(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountFollowings, followerID)
	var following_count int64
	err := row.Scan(&following_count)
	return following_count, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT f.follower_id, f.created_at, u.username 
FROM followers f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $1
ORDER BY f.created_at DESC
`

type GetFollowersRow struct {
	FollowerID uuid.UUID
	CreatedAt  time.Time
	Username   string
}

func (q *Queries) GetFollowers(ctx context.Context, followeeID uuid.UUID) ([]GetFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(&i.FollowerID, &i.CreatedAt, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersEmail = `-- name: GetFollowersEmail :many
SELECT u.id , u.email
FROM followers f
JOIN users u ON u.id = f.follower_id 
WHERE f.followee_id = $1
ORDER BY f.created_at DESC
`

type GetFollowersEmailRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) GetFollowersEmail(ctx context.Context, followeeID uuid.UUID) ([]GetFollowersEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowersEmail, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersEmailRow
	for rows.Next() {
		var i GetFollowersEmailRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowings = `-- name: GetFollowings :many
SELECT f.followee_id, f.created_at, u.username
FROM followers f
JOIN users u ON u.id = f.followee_id 
WHERE f.follower_id = $1 
ORDER BY f.created_at DESC
`

type GetFollowingsRow struct {
	FolloweeID uuid.UUID
	CreatedAt  time.Time
	Username   string
}

func (q *Queries) GetFollowings(ctx context.Context, followerID uuid.UUID) ([]GetFollowingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowings, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingsRow
	for rows.Next() {
		var i GetFollowingsRow
		if err := rows.Scan(&i.FolloweeID, &i.CreatedAt, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM followers 
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
