// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNotifications = `-- name: CreateNotifications :one
INSERT INTO notifications (created_at, body, receiver, triggerer, chirp_id)
VALUES (
    NOW(),
    $1, $2, $3, $4
)
RETURNING id, created_at, body, receiver, triggerer, chirp_id, is_read
`

type CreateNotificationsParams struct {
	Body      string
	Receiver  uuid.UUID
	Triggerer uuid.UUID
	ChirpID   uuid.UUID
}

func (q *Queries) CreateNotifications(ctx context.Context, arg CreateNotificationsParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotifications,
		arg.Body,
		arg.Receiver,
		arg.Triggerer,
		arg.ChirpID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Body,
		&i.Receiver,
		&i.Triggerer,
		&i.ChirpID,
		&i.IsRead,
	)
	return i, err
}

const createNotificationsBulk = `-- name: CreateNotificationsBulk :exec
INSERT INTO notifications (body, receiver, triggerer, chirp_id, created_at)
SELECT $1, unnest($2::uuid[]), $3, $4, NOW()
`

type CreateNotificationsBulkParams struct {
	Body      string
	Column2   []uuid.UUID
	Triggerer uuid.UUID
	ChirpID   uuid.UUID
}

func (q *Queries) CreateNotificationsBulk(ctx context.Context, arg CreateNotificationsBulkParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationsBulk,
		arg.Body,
		pq.Array(arg.Column2),
		arg.Triggerer,
		arg.ChirpID,
	)
	return err
}

const getNotificationByReceiver = `-- name: GetNotificationByReceiver :many
SELECT n.id, n.created_at, n.body, n.receiver, n.triggerer, n.chirp_id, n.is_read, u.username
FROM notifications n 
JOIN users u ON u.id = n.triggerer
WHERE n.receiver = $1
ORDER BY n.created_at DESC
`

type GetNotificationByReceiverRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Body      string
	Receiver  uuid.UUID
	Triggerer uuid.UUID
	ChirpID   uuid.UUID
	IsRead    bool
	Username  string
}

func (q *Queries) GetNotificationByReceiver(ctx context.Context, receiver uuid.UUID) ([]GetNotificationByReceiverRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationByReceiver, receiver)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationByReceiverRow
	for rows.Next() {
		var i GetNotificationByReceiverRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Body,
			&i.Receiver,
			&i.Triggerer,
			&i.ChirpID,
			&i.IsRead,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications
SET is_read = true 
WHERE receiver = $1
`

func (q *Queries) MarkAllAsRead(ctx context.Context, receiver uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllAsRead, receiver)
	return err
}

const markOneAsRead = `-- name: MarkOneAsRead :exec
UPDATE notifications 
SET is_read = true
WHERE id = $1 AND receiver = $2
`

type MarkOneAsReadParams struct {
	ID       uuid.UUID
	Receiver uuid.UUID
}

func (q *Queries) MarkOneAsRead(ctx context.Context, arg MarkOneAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markOneAsRead, arg.ID, arg.Receiver)
	return err
}
