// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO reactions (chirp_id, user_id, type)
VALUES ($1, $2, $3)
ON CONFLICT (chirp_id, user_id)
DO UPDATE SET type = EXCLUDED.type 
RETURNING chirp_id, user_id, type, created_at
`

type AddReactionParams struct {
	ChirpID uuid.UUID
	UserID  uuid.UUID
	Type    string
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, addReaction, arg.ChirpID, arg.UserID, arg.Type)
	var i Reaction
	err := row.Scan(
		&i.ChirpID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionCounts = `-- name: GetReactionCounts :many
SELECT type, COUNT(*) as count
FROM reactions
WHERE chirp_id = $1
GROUP BY type 
ORDER BY count DESC
`

type GetReactionCountsRow struct {
	Type  string
	Count int64
}

func (q *Queries) GetReactionCounts(ctx context.Context, chirpID uuid.UUID) ([]GetReactionCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReactionCounts, chirpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionCountsRow
	for rows.Next() {
		var i GetReactionCountsRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionTotal = `-- name: GetReactionTotal :one
SELECT COUNT(*) AS total
FROM reactions
WHERE chirp_id = $1
`

func (q *Queries) GetReactionTotal(ctx context.Context, chirpID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReactionTotal, chirpID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getReactionsByChirpID = `-- name: GetReactionsByChirpID :many
SELECT r.chirp_id, r.user_id, r.type, r.created_at, u.username
FROM reactions r 
JOIN users u ON u.id = r.user_id
WHERE r.chirp_id = $1
ORDER BY r.created_at DESC
`

type GetReactionsByChirpIDRow struct {
	ChirpID   uuid.UUID
	UserID    uuid.UUID
	Type      string
	CreatedAt time.Time
	Username  string
}

func (q *Queries) GetReactionsByChirpID(ctx context.Context, chirpID uuid.UUID) ([]GetReactionsByChirpIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getReactionsByChirpID, chirpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionsByChirpIDRow
	for rows.Next() {
		var i GetReactionsByChirpIDRow
		if err := rows.Scan(
			&i.ChirpID,
			&i.UserID,
			&i.Type,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReactions = `-- name: GetUserReactions :one
SELECT type 
FROM reactions 
WHERE chirp_id = $1 AND user_id = $2
`

type GetUserReactionsParams struct {
	ChirpID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetUserReactions(ctx context.Context, arg GetUserReactionsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserReactions, arg.ChirpID, arg.UserID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const removeReaction = `-- name: RemoveReaction :one
DELETE FROM reactions
WHERE chirp_id = $1 AND user_id = $2
RETURNING chirp_id, user_id, type, created_at
`

type RemoveReactionParams struct {
	ChirpID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, removeReaction, arg.ChirpID, arg.UserID)
	var i Reaction
	err := row.Scan(
		&i.ChirpID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
