# stage 1 - build
FROM golang:1.23-alpine AS builder

WORKDIR /app 

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o workers ./cmd/workers

# stage 2 - final image
FROM alpine:latest 

WORKDIR /app

COPY --from=builder /app/workers .

EXPOSE 8080 

CMD [ "./workers" ]