services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cardinal
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    
  server:
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    env_file: .env.docker
    depends_on:
      - postgres
      - rabbitmq
  
  workers:
    build: 
      context: .
      dockerfile: Dockerfile.workers
    env_file: .env.docker
    depends_on:
      - postgres
      - rabbitmq
