# stage 1 - build
FROM golang:1.25 AS builder

WORKDIR /app 

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o workers ./cmd/workers

# stage 2 - final image
FROM alpine:latest 

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/workers .

EXPOSE 8080 

CMD [ "/app/workers" ]