-- +goose Up
ALTER TABLE chirps
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_chirps_user_id ON chirps(user_id);

-- +goose Down
DROP INDEX IF EXISTS idx_chirps_user_id;

ALTER TABLE chirps
ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE,
ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE;
